/* CAT EMPIRE — compatibilidade mobile / WebView */
(function () {
  'use strict';
  const mediaDevices = navigator.mediaDevices;
  if (mediaDevices && typeof mediaDevices.getUserMedia === 'function') {
    const originalGetUserMedia = mediaDevices.getUserMedia.bind(mediaDevices);
    let activeCameraStream = null, activeCameraDeviceId = null;
    const hasVideo=c=>!!c&&!!c.video&&typeof c.video==='object';
    const copy=v=>v&&typeof v==='object'?{...v}:{};
    const remember=s=>{const t=s?.getVideoTracks?.()[0];if(!t)return s;activeCameraStream=s;try{activeCameraDeviceId=t.getSettings().deviceId||null}catch{activeCameraDeviceId=null}t.addEventListener('ended',()=>{if(activeCameraStream===s)activeCameraStream=null},{once:true});return s};
    async function specific(c,id){const v=copy(c.video);delete v.facingMode;v.deviceId={exact:id};return originalGetUserMedia({...c,video:v})}
    mediaDevices.getUserMedia=async c=>{if(!hasVideo(c))return originalGetUserMedia(c);const prev=activeCameraDeviceId;if(activeCameraStream){activeCameraStream.getVideoTracks().forEach(t=>{try{t.stop()}catch{}});activeCameraStream=null}try{return remember(await originalGetUserMedia(c))}catch(first){const facing=typeof c.video.facingMode==='string'?c.video.facingMode:(c.video.facingMode&&(c.video.facingMode.exact||c.video.facingMode.ideal));try{const ds=await mediaDevices.enumerateDevices(),cams=ds.filter(d=>d.kind==='videoinput').filter(d=>!prev||d.deviceId!==prev),labels=cams.map(d=>({d,label:(d.label||'').toLowerCase()}));const p=facing==='environment'?labels.find(x=>/back|rear|traseira|environment|c[aâ]mera\s*2/.test(x.label)):labels.find(x=>/front|user|frontal|selfie|c[aâ]mera\s*1/.test(x.label));if((p?.d||cams[0]))return remember(await specific(c,(p?.d||cams[0]).deviceId))}catch{}if(facing==='user'||facing==='environment')try{const v=copy(c.video);v.facingMode={exact:facing};return remember(await originalGetUserMedia({...c,video:v}))}catch{}if(prev)try{return remember(await specific(c,prev))}catch{}throw first}}
  }
  function ensureInvite(){if(document.getElementById('inviteModal'))return;const m=document.createElement('div');m.className='modal';m.id='inviteModal';m.innerHTML='<div class="modal-box"><h2>🔗 Convidar para o servidor</h2><p class="modal-hint">Compartilhe este link para outras pessoas entrarem neste servidor.</p><div class="kv-row"><span class="kv-value" id="inviteLinkText" style="flex:1;word-break:break-all">Gerando link…</span><button class="btn kv-copy" id="copyInviteBtn">Copiar</button></div><div class="modal-actions"><button class="btn btn-primary" id="closeInviteModalBtn">Fechar</button></div></div>';document.body.appendChild(m)}
  ensureInvite();
  function post(){document.querySelector('#viewProfileModal .modal-box')?.classList.add('profile-horizontal');const b=document.getElementById('serverInviteBtn'),r=document.querySelector('#serverHead .server-head-row');if(b&&r&&!b.dataset.compact){b.dataset.compact='1';b.textContent='👥+';b.title='Convidar para o servidor';Object.assign(b.style,{width:'38px',height:'34px',padding:'0',fontSize:'13px',display:'grid',placeItems:'center',flex:'none'});r.appendChild(b)}}
  function load(){if(document.getElementById('catEmpireEnhancementsScript'))return;const e=document.createElement('script');e.id='catEmpireEnhancementsScript';e.src='/enhancements.js?v=20260821';e.async=false;e.onload=()=>{const v2=document.createElement('script');v2.id='catEmpireFeaturesV2Script';v2.src='/features-v2.js?v=20260821';v2.async=false;v2.onload=()=>{const v3=document.createElement('script');v3.id='catEmpireFeaturesV3Script';v3.src='/features-v3.js?v=20260821';v3.async=false;v3.onload=()=>{const f=document.createElement('script');f.src='/features-v3-fix.js?v=20260821';f.async=false;document.body.appendChild(f)};document.body.appendChild(v3)};document.body.appendChild(v2);setTimeout(post,400)};document.body.appendChild(e)}
  if(document.readyState==='complete')load();else window.addEventListener('load',load,{once:true});
})();
