(() => {
  if (!document.getElementById('serverSettingsBtn')) return;
  const $=id=>document.getElementById(id), q=new URLSearchParams(location.search), sid=q.get('serverId'), token=localStorage.getItem('cat_token')||'';
  const api=async(u,o={})=>{const r=await fetch(u,{...o,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(o.headers||{})}});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||'Erro');return d};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function open(){
    document.getElementById('catV3Settings')?.remove();
    const o=document.createElement('div');o.className='feature-settings-overlay open';o.id='catV3Fixed';
    o.innerHTML='<aside class="feature-settings-nav"><div class="feature-settings-brand">CAT EMPIRE<small>CONFIGURAÇÕES DO SERVIDOR</small></div><div class="feature-nav-group">SERVIDOR</div><button class="feature-nav-btn active" data-p="overview">Perfil do servidor</button><button class="feature-nav-btn" data-p="channels">Canais e categorias</button><div class="feature-nav-group">PESSOAS</div><button class="feature-nav-btn" data-p="members">Membros</button><button class="feature-nav-btn" data-p="roles">Cargos</button><div class="feature-nav-group">MODERAÇÃO</div><button class="feature-nav-btn" data-p="security">Configurações de segurança</button></aside><main class="feature-settings-main"><button class="feature-settings-close" id="fixedClose">×</button><div id="fixedContent"></div></main></div>';
    document.body.appendChild(o);o.querySelectorAll('.feature-nav-btn').forEach(b=>b.onclick=()=>page(b.dataset.p));$('fixedClose').onclick=()=>o.remove();page('overview');
  }
  async function page(p){const c=$('fixedContent');document.querySelectorAll('#catV3Fixed .feature-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.p===p));if(p==='overview')overview(c);else if(p==='channels')channels(c);else if(p==='members')members(c);else if(p==='roles')roles(c);else security(c)}
  async function overview(c){const d=await api('/api/features/servers/'+sid+'/settings');c.innerHTML='<div class="v3-title">Perfil do servidor</div><div class="v3-sub">Configurações no mesmo visual do CAT EMPIRE.</div><div class="v3-card"><div class="v3-field"><label>NOME</label><input id="fxName" value="'+esc(d.name)+'"></div><div class="v3-field"><label>DESCRIÇÃO</label><textarea id="fxDesc">'+esc(d.description||'')+'</textarea></div><div class="v3-actions"><button class="v3-btn" id="fxCancel">Cancelar</button><button class="v3-btn primary" id="fxSave">Salvar alterações</button></div></div>';$('fxCancel').onclick=()=>$('catV3Fixed').remove();$('fxSave').onclick=async()=>{try{const x=await api('/api/servers/'+sid,{method:'PUT',body:JSON.stringify({name:$('fxName').value.trim(),description:$('fxDesc').value})});$('serverName').textContent=x.name;window.applyBannerStyle?.($('serverHead'),x.banner_color);$('catV3Fixed').remove();toast?.('Servidor atualizado.','success')}catch(e){toast?.(e.message,'error')}}}
  async function channels(c){c.innerHTML='<div class="v3-title">Canais e categorias</div><div class="v3-sub">Crie e edite categorias e canais.</div><div class="v3-card"><div class="v3-field"><label>NOVA CATEGORIA</label><input id="fxCat"></div><button class="v3-btn primary" id="fxCatBtn">Criar categoria</button></div><div id="fxCats">Carregando…</div>';$('fxCatBtn').onclick=async()=>{const n=$('fxCat').value.trim();if(!n)return;try{await api('/api/features/servers/'+sid+'/categories',{method:'POST',body:JSON.stringify({name:n})});channels(c);window.renderChannelList?.()}catch(e){toast?.(e.message,'error')}};try{const d=await api('/api/features/servers/'+sid+'/categories');const cats=d.categories||d,chs=d.channels||[];$('fxCats').innerHTML=cats.map(cat=>'<div class="v3-card"><div class="v3-row"><b class="grow">'+esc(cat.name)+'</b><button class="v3-mini" data-r="'+cat.id+'">Editar</button><button class="v3-mini" data-d="'+cat.id+'">Excluir</button></div>'+chs.filter(x=>(x.category||'CANAIS')===cat.name).map(ch=>'<div class="v3-row"><span>'+(ch.type==='voice'?'🔊':'#')+'</span><span class="grow">'+esc(ch.name)+'</span><button class="v3-mini" data-c="'+ch.id+'">Editar</button><button class="v3-mini" data-x="'+ch.id+'">Excluir</button></div>').join('')+'</div>').join('');document.querySelectorAll('#fxCats [data-r]').forEach(b=>b.onclick=async()=>{const cat=cats.find(x=>x.id===b.dataset.r),n=prompt('Nome da categoria:',cat?.name||'');if(n)api('/api/features/servers/'+sid+'/categories/'+b.dataset.r,{method:'PUT',body:JSON.stringify({name:n})}).then(()=>channels(c)).catch(e=>toast?.(e.message,'error'))});document.querySelectorAll('#fxCats [data-d]').forEach(b=>b.onclick=async()=>{if(await uiConfirm('Excluir categoria?'))api('/api/features/servers/'+sid+'/categories/'+b.dataset.d,{method:'DELETE'}).then(()=>channels(c)).catch(e=>toast?.(e.message,'error'))});document.querySelectorAll('#fxCats [data-c]').forEach(b=>b.onclick=async()=>{const n=prompt('Novo nome do canal:');if(n)api('/api/features/servers/'+sid+'/channels/'+b.dataset.c,{method:'PUT',body:JSON.stringify({name:n})}).then(()=>channels(c)).catch(e=>toast?.(e.message,'error'))});document.querySelectorAll('#fxCats [data-x]').forEach(b=>b.onclick=async()=>{if(await uiConfirm('Excluir canal?'))api('/api/servers/'+sid+'/channels/'+b.dataset.x,{method:'DELETE'}).then(()=>channels(c)).catch(e=>toast?.(e.message,'error'))})}catch(e){$('fxCats').textContent=e.message}}
  async function members(c){const d=await api('/api/servers/'+sid);c.innerHTML='<div class="v3-title">Membros</div><div class="v3-sub">Gerencie os membros e sua hierarquia.</div><div id="fxMembers" class="v3-card">'+d.members.map(m=>'<div class="v3-row"><span class="grow">'+esc(m.display_name||m.username)+'</span><span class="v3-role">'+(d.creator_id===m.id?'FOUNDER':m.role==='admin'?'ADMIN':'MEMBRO')+'</span>'+((d.creator_id===m.id||m.id===localStorage.getItem('cat_user_id'))?'':'<button class="v3-mini" data-m="'+m.id+'">'+(m.role==='admin'?'Rebaixar':'Promover')+'</button>')+'</div>').join('')+'</div>';document.querySelectorAll('#fxMembers [data-m]').forEach(b=>b.onclick=async()=>{const m=d.members.find(x=>x.id===b.dataset.m);await api('/api/servers/'+sid+'/members/'+b.dataset.m+'/role',{method:'PUT',body:JSON.stringify({role:m.role==='admin'?'member':'admin'})});members(c)})}
  async function roles(c){const d=await api('/api/features/servers/'+sid+'/roles');c.innerHTML='<div class="v3-title">Cargos</div><div class="v3-sub">Hierarquia atual do servidor.</div>'+d.roles.map(r=>'<div class="v3-card"><div class="v3-row"><b style="color:'+r.color+'">'+r.name+'</b><span class="grow"></span><span class="v3-role">'+r.count+'</span></div><div style="font:8px monospace;color:#8d7ba9">'+esc(r.description)+'</div></div>').join('')}
  async function security(c){const d=await api('/api/features/servers/'+sid+'/settings'),s={verification:false,mediaFilter:false,mentions:false,...(d.security||{})};c.innerHTML='<div class="v3-title">Configurações de segurança</div><div class="v3-sub">Salvas no Postgres.</div><div id="fxSec">'+[['verification','Verificação de entrada'],['mediaFilter','Filtro de mídia'],['mentions','Controle de menções']].map(x=>'<div class="v3-toggle"><span>'+x[1]+'</span><button data-s="'+x[0]+'" class="'+(s[x[0]]?'on':'')+'">'+(s[x[0]]?'ATIVO':'DESATIVADO')+'</button></div>').join('')+'<div class="v3-actions"><button class="v3-btn primary" id="fxSecSave">Salvar segurança</button></div></div>';document.querySelectorAll('#fxSec [data-s]').forEach(b=>b.onclick=()=>{s[b.dataset.s]=!s[b.dataset.s];b.classList.toggle('on',s[b.dataset.s]);b.textContent=s[b.dataset.s]?'ATIVO':'DESATIVADO'});$('fxSecSave').onclick=()=>api('/api/features/servers/'+sid+'/settings',{method:'PUT',body:JSON.stringify({security:s})}).then(()=>toast?.('Segurança salva.','success')).catch(e=>toast?.(e.message,'error'))}
  $('serverSettingsBtn').onclick=e=>{e.preventDefault();open()};
})();
